### PR TITLE
Add comment view to support comment section

### LINKED ISSUE #75: Add comment section in collection page
Make user can comment to each other's collection. This issues will close when all checklists is complete.

Frontend:
- [x] #76

Backend:
- [x] #77

### LINKED ISSUE #77: Add comment progress in collection view
- [ ] Depends on #74 

Backend will bind with database value to finish comment part.

### PR DESCRIPTION
**Pull request by HelloYeew**
Close #75 and Close #77

Hi! I just finish binding the comment section with the view that I write so now we can comment on the collection!

image

### CODE REVIEW

**Review by pontakornth — APPROVED** [review]
I tested. It works.

**Review by SainTurDaY27 — APPROVED** [review]
Nice comment section!

**Review by Siraphop4Nene — APPROVED** [review]

**Review by some-random-idiot — APPROVED** [review]
Lovely. Nice design!

**Comment by HelloYeew** [comment]
Let's merge!

**Pull request merged**
