### PR TITLE
Create embeddable collection card and beatmap card

### PR DESCRIPTION
**Pull request by pontakornth**
It is working on desktop but has width issue on mobile. Can anyone help me with that?

image

image

### CODE REVIEW

**Comment by HelloYeew** [comment]
I think the problem with mobile is not important because the iframe always has problem with mobile devide. It's depend on user's setting when embed too.

**Review by HelloYeew — APPROVED** [review]
Looking good!

**Review by SainTurDaY27 — APPROVED** [review]

**Review by Siraphop4Nene — APPROVED** [review]
Nice work kub.

**Review by some-random-idiot — APPROVED** [review]

**Comment by HelloYeew** [comment]
Let's try it!

**Pull request merged**
