### PR TITLE
Add edit and delete comment and fix some UX

### LINKED ISSUE #185: Make edit comment on beatmap card feature
Allow user who add the beatmap to edit his/her comment on the card.

### LINKED ISSUE #186: Design the edit beatmap comment system
Before #185 we must make the design on this function.

### LINKED ISSUE #187: Make the delete comment function system
Let website staff, comment owner and collection owner delete the comment on the collection.

### LINKED ISSUE #209: Add "See all" button on the home page
It's difficult to know about listing if the user is not paying attention. If there is a "See all" button at the bottom of homepage, user would navigate the web easier.

### LINKED ISSUE #210: Add animation to paginator
I forgot to add the animation. The paginator looks weird without it.

### PR DESCRIPTION
**Pull request by HelloYeew**
Hi! This is the bug update on CRUD operation on comment system!

# Delete & Edit comment system

image

## Delete comment

Close #187

User who can delete comment is staff, superuser and comment owner

## Edit comment

image

User who can delete comment is only comment owner.

## Edit comment on beatmap card or `BeatmapEntry`

Close #185 and Close #186

image

- The edit comment will available in manage beatmap page in collection
- The button to edit comment will only show when collection is turned the allow comment on only.
- User allow to delete comment in the card to (edit, delete comment and save)

About Delete & Edit comment system, Edit comment on beatmap card I have written all test, please check on the correction too.

# Add "See all" button on the home page

Close #209

image

# Add animation to paginator

Close #210

# More UI improvement

- Add best wallpaper to random list and change homepage image back to random
- Improve SUS algorithm to less chance!

# More reliability on database improvement

- Make `comment` in BeatmapEntry can be exactly null

# Performance and repository cleaning

- Delete some unused file
- Resize some picture that still can resize

### CODE REVIEW

**Review by Siraphop4Nene — APPROVED** [review]

**Review by pontakornth — APPROVED** [review]
It works fine. I can approve this even it's still sus.

**Review by some-random-idiot — APPROVED** [review]
Sus or not the option to edit and delete comments is a very good addition!

**Review by SainTurDaY27 — APPROVED** [review]
I hope this features work well with comments.
Especially SUS comments.
Good job!

**Comment by HelloYeew** [comment]
Let's merge this SUS!

**Pull request merged**
