### PR TITLE
Add support for osu! profile migration when signed up for website with osu! OAuth

### LINKED ISSUE #90: Make profile from osu! migrate when user sign up with osu! account
When user sign up with osu! account, we must make migration from osu! profile to our profile.

### PR DESCRIPTION
**Pull request by HelloYeew**
Close #90 

Now when user signed up using osu! OAuth, the signals will get an information that can fill in `Profile` to user's profile.

### CODE REVIEW

**Review by Siraphop4Nene — APPROVED** [review]
I love this code. Thank you

**Review by SainTurDaY27 — APPROVED** [review]
#112 is a good improvement on our website!
Nice!

**Review by pontakornth — APPROVED** [review]
Great job. Unfortunately, this only works on production.

**Review by some-random-idiot — APPROVED** [review]
Nice improvement. Good job!

**Comment by HelloYeew** [comment]
Let's merge now!

**Pull request merged**
