### PR TITLE
Add mapper profile picture to infobox

### LINKED ISSUE #136: Show profile picture of mapper on infobox.
- [ ] Depends on #137 

On osu! website show the profile picture of mapper on the approve and update date. This might need to improve too.

### LINKED ISSUE #137: Make a function to fetch user profiles using an API
To make #137 possible we need to take a glance on osu! user API to fetch the profile picture url and put in on `Beatmap` model on database.

### PR DESCRIPTION
**Pull request by HelloYeew**
Close #136 and Close #137

I just add mapper's profile picture to infobox to make it like open osu! website.

CleanShot 2564-11-07 at 16 37 23@2x

### CODE REVIEW

**Review by pontakornth — APPROVED** [review]
Great. I will handle the refactoring in my PR.

**Review by pontakornth — APPROVED** [review]

**Review by some-random-idiot — APPROVED** [review]
Good work!

**Review by SainTurDaY27 — APPROVED** [review]
Nice improvement. Good work!

**Review by Siraphop4Nene — APPROVED** [review]

**Comment by HelloYeew** [comment]
Let's merge it!

**Pull request merged**
