### PR TITLE
Add Social sharing and fix collection text in profile page

### LINKED ISSUE #132: The profile page is still show username's collection text despite no collection.
CleanShot 2564-11-06 at 19 49 14@2x

The profile page is still show collection's header despite no collection on the profile page.

### LINKED ISSUE #135: Create share using social network button
Make a button that can click to make the collection and profile can share on other social networ platform like Facebook (Make a new post with a link) or Twitter (Make a new tweet).

### PR DESCRIPTION
**Pull request by pontakornth**
Closes #135 
Fix #132 

Add sharing button to collection page and profile page. Also fix the collection text is still show despite no collection in profile page.
image

### CODE REVIEW

**Comment by pontakornth** [comment]
Screen Shot 2564-11-09 at 12 31 47

Screenshot

**Review by HelloYeew — CHANGES_REQUESTED** [review]
You forget the profile page but lemme do it.

**Review by HelloYeew — APPROVED** [review]

**Review by SainTurDaY27 — APPROVED** [review]
Good work!

**Review by some-random-idiot — APPROVED** [review]
Good addition, nice work!

**Review by Siraphop4Nene — APPROVED** [review]

**Comment by HelloYeew** [comment]
Merging!

**Pull request merged**
