### PR TITLE
Add beatmap approval system

### LINKED ISSUE #81: Add beatmap approval system
Add system that collection user can manage to approve or deny beatmap that other user want to add to your collection. This issue will be close when all checklist is complete.

Frontend:
- [x] #82

Backend:
- [x] #83

### LINKED ISSUE #82: Make mockup on beatmap approval page
Frontend make mockup on beatmap approval page.

### LINKED ISSUE #83: Bind beatmap approval page mockup with the view
- [ ] Depends on #82

After finish mockup in #82, backend will bind it with the complete view to make this function work.

### PR DESCRIPTION
**Pull request by HelloYeew**
Hi, I just add beatmap approval system. Now other user can add a beatmap to a collection but the owner need to approve it before it's show on collection.

## Changes on database

Now every beatmap will be fallback to not approve state since the default value of `owner_approved` field in `BeatmapEntry` is False.

### CODE REVIEW

**Review by pontakornth — APPROVED** [review]
Work for me. Good tests

Note: After merging, we need to approve all existing beatmaps. Otherwise, it will display blank pages.

**Review by pontakornth — APPROVED** [review]
@HelloYeew requested my review again. Same answer.

**Review by Siraphop4Nene — APPROVED** [review]

**Review by some-random-idiot — APPROVED** [review]
Everything looks fine. Approved!

**Review by SainTurDaY27 — APPROVED** [review]
Nice work!

**Pull request merged**
