### PR TITLE
Refactor conditions to dictionary lookup

### PR DESCRIPTION
**Pull request by pontakornth**
I noticed that some conditions can be replaced by dictionary lookup. So, I replace them with filters.

Originally, I intend to use property but demo card does not use model.

### CODE REVIEW

**Comment by pontakornth** [comment]
Currently, not everything has been refactored now. If anyone wishes to do this further, you can use this as a guideline.

**Review by HelloYeew — APPROVED** [review]
Looking and test on it and it's better!

**Review by SainTurDaY27 — APPROVED** [review]
Code is clean! Good!

**Review by some-random-idiot — APPROVED** [review]
Good improvement!

**Review by Siraphop4Nene — APPROVED** [review]

**Comment by HelloYeew** [comment]
Let's merge it!

**Pull request merged**
