### PR TITLE
Add Member page

### LINKED ISSUE #192: Make a member page
On the conversation on Discord, we think that if we have a member page it will be better.

### PR DESCRIPTION
**Pull request by HelloYeew**
Close #192 

Hi! From the team discussion I make the team page and make the styling as you send the information to me. Now you can check it!

image

### CODE REVIEW

**Review by Siraphop4Nene — APPROVED** [review]
I love sea with dog.

**Review by SainTurDaY27 — APPROVED** [review]
@SainTurDaY27 said that this is G O O D !

**Review by some-random-idiot — APPROVED** [review]
Very good!

**Review by pontakornth — APPROVED** [review]
Look great to me.

**Pull request merged**
