### PR TITLE
Add live beatmap card render on adding beatmap page

### LINKED ISSUE #91: Add live render beatmap card on add beatmap page
Add user can see mock beatmapcard after adding to collection. This is the forward step to our target that don't want user to open osu! website when adding beatmap.

### PR DESCRIPTION
**Pull request by HelloYeew**
Close #91 

Hello! I add the live beatmap demo when user adding beatmap by filling the beatmap ID to the field. You can see the demo here!

https://user-images.githubusercontent.com/68165621/140275873-1b7a7ece-c149-4371-ac72-11ce404efac4.mp4

### CODE REVIEW

**Review by pontakornth — APPROVED** [review]
Great job. I still have no idea how to refactor `star_rating_color_demo`. If anyone has an idea, please create PR.

**Review by some-random-idiot — APPROVED** [review]

**Review by Siraphop4Nene — APPROVED** [review]
Blowjob kub

**Review by SainTurDaY27 — APPROVED** [review]
Attached mp4 can describe this PR well.
Nice work - Good code!

**Comment by HelloYeew** [comment]
Let's try it!

**Pull request merged**
