### PR TITLE
Fix more sweden bug

### PR DESCRIPTION
**Pull request by HelloYeew**
After we try on adding same comment and it's still error so this is the second attempt we fix on this

### CODE REVIEW

**Review by pontakornth — APPROVED** [review]
Yes, no more Sweden bug.

**Review by some-random-idiot — APPROVED** [review]
Sweden

**Review by Siraphop4Nene — APPROVED** [review]
But I love japan!!!

**Review by SainTurDaY27 — APPROVED** [review]
sWEDEN iS gREAT!

**Pull request merged**
