### PR TITLE
Revamp the website theme and wallpaper

### PR DESCRIPTION
**Pull request by HelloYeew**
From the discussion, we want to make the user always have the unique feeling in every session and every page. That's why me and @SainTurDaY27 revamp the wallpaper and make it always random. The new wallpaper location will locate in `static/img/hero`. To make the shuffle easier, the picture will use the name as <int>.jpg. The 2 page that not effect from this change is collection and profile page (that is custom by user).

### CODE REVIEW

**Review by pontakornth — APPROVED** [review]
Nice change.

**Review by SainTurDaY27 — APPROVED** [review]
This change is fantastic!!!

**Review by some-random-idiot — APPROVED** [review]
Lovely!

**Review by Siraphop4Nene — APPROVED** [review]

**Comment by HelloYeew** [comment]
Let's do it!

**Pull request merged**
