### PR TITLE
Second attempt to fix value too long for type character varying

### PR DESCRIPTION
**Pull request by HelloYeew**
After #122 I try to run it and I still get an error but better understanding by the new traceback log that I just add in #122. So I finally investigate it and I try to fix it. Hope this fix...

### CODE REVIEW

**Review by Siraphop4Nene — APPROVED** [review]

**Review by SainTurDaY27 — APPROVED** [review]
Good Good Good!!!

**Review by some-random-idiot — APPROVED** [review]
Lovely.

**Review by pontakornth — APPROVED** [review]
So, you increase the field size. That's understandable. Some beatmap name is really long just like a snake.

**Comment by HelloYeew** [comment]
Let's try on it again!

**Pull request merged**
